//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MusicOre.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LibraryEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LibraryEntities object using the connection string found in the 'LibraryEntities' section of the application configuration file.
        /// </summary>
        public LibraryEntities() : base("name=LibraryEntities", "LibraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LibraryEntities object.
        /// </summary>
        public LibraryEntities(string connectionString) : base(connectionString, "LibraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LibraryEntities object.
        /// </summary>
        public LibraryEntities(EntityConnection connection) : base(connection, "LibraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StartupParam> StartupParams
        {
            get
            {
                if ((_StartupParams == null))
                {
                    _StartupParams = base.CreateObjectSet<StartupParam>("StartupParams");
                }
                return _StartupParams;
            }
        }
        private ObjectSet<StartupParam> _StartupParams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StartupParams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStartupParams(StartupParam startupParam)
        {
            base.AddObject("StartupParams", startupParam);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="StartupParam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StartupParam : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StartupParam object.
        /// </summary>
        /// <param name="paramName">Initial value of the ParamName property.</param>
        /// <param name="paramValue">Initial value of the ParamValue property.</param>
        public static StartupParam CreateStartupParam(global::System.String paramName, global::System.String paramValue)
        {
            StartupParam startupParam = new StartupParam();
            startupParam.ParamName = paramName;
            startupParam.ParamValue = paramValue;
            return startupParam;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParamName
        {
            get
            {
                return _ParamName;
            }
            set
            {
                if (_ParamName != value)
                {
                    OnParamNameChanging(value);
                    ReportPropertyChanging("ParamName");
                    _ParamName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ParamName");
                    OnParamNameChanged();
                }
            }
        }
        private global::System.String _ParamName;
        partial void OnParamNameChanging(global::System.String value);
        partial void OnParamNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParamValue
        {
            get
            {
                return _ParamValue;
            }
            set
            {
                OnParamValueChanging(value);
                ReportPropertyChanging("ParamValue");
                _ParamValue = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ParamValue");
                OnParamValueChanged();
            }
        }
        private global::System.String _ParamValue;
        partial void OnParamValueChanging(global::System.String value);
        partial void OnParamValueChanged();

        #endregion
    
    }

    #endregion
    
}
